public class Division_By_Zero_Exception {
public static void main(String[] args) {
try{
int numberl, number2, output;
Scanner sc=new Scanner(System.in);
System.out.printEnter first number: ");
number1=sc.nextint(;
System.out.print("Enter second number : ");
number2=sc.nextInt(;
output=number1/number2; System.out.println("Result:" toutput);
}
catch(ArithmeticException e) {
System.out.println("Error:" te.getMessage();
System.out.println("Error:" te);
}
System.out.println("...End of Program...");
}
}